// All HTTP APIs are mocked. This script never mutates production data.
async page => {
  const origin = 'http://127.0.0.1:5199';
  await page.unroute('**/api/**');
  const check = (condition, label) => { if (!condition) throw new Error(label); };
  const errors = [], writes = [], results = [];
  let fail = '', empty = false, failDelivery = false, release, pending = false;
  const image = origin + '/favicon-96.png';
  const posts = [{ id: 12, title: '함께한 첫 산책', content: '입양 후 일상을 기록합니다.', authorId: 3, authorName: '예시 회원', authorNickname: '포우친구', boardType: 'ADOPTION', createdAt: '2026-10-01T10:00:00', imageUrls: [image], viewCount: 24 }];
  let categories = [{ id: 1, name: '강아지', description: '용품 분류', parentId: null, children: [{ id: 2, name: '산책용품', description: '', parentId: 1, children: [] }] }];
  let groups = [{ id: 1, name: '사이즈', values: [{ id: 1, groupId: 1, groupName: '사이즈', name: 'S' }, { id: 2, groupId: 1, groupName: '사이즈', name: 'M' }] }];
  const product = { productId: 1, name: '산책 하네스', description: '안전한 산책을 위한 상품', imageUrl: image, status: 'ACTIVE', categoryId: 1, skus: [{ skuId: 2, skuCode: 'HAR-S', price: 19000, stockQuantity: 12, optionValueIds: [1], options: { 사이즈: 'S' } }] };
  let order = { orderId: 1, orderUuid: 'PB-TEST-0001', userId: 10, totalAmount: 38000, status: 'PAID', deliveryStatus: 'READY', receiverName: '예시 수령인', receiverPhone: '010-0000-0000', deliveryAddress: '예시 주소 '.repeat(20), deliveryMessage: '문 앞', createdAt: '2026-10-01T10:00:00', items: [{ productName: product.name, skuCode: 'HAR-S', price: 19000, quantity: 2 }] };
  const paged = content => ({ content, totalElements: content.length, totalPages: content.length ? 1 : 0, number: 0, size: 20, first: true, last: true, empty: !content.length });
  const envelope = data => ({ code: 200, data });
  page.on('pageerror', error => errors.push(error.message));
  await page.route('**/api/**', async route => {
    const request = route.request();
    if (!['xhr', 'fetch'].includes(request.resourceType())) return route.continue();
    const path = request.url().replace(/^https?:\/\/[^/]+/, '').split('?')[0];
    if (request.method() !== 'GET') {
      const raw = request.postData();
      const json = request.headers()['content-type']?.includes('application/json') ? request.postDataJSON() : null;
      writes.push({ path, method: request.method(), json, raw });
      if (pending) await new Promise(resolve => { release = resolve; });
      if (failDelivery && path.endsWith('/delivery-status')) return route.fulfill({ status: 500, json: { message: 'mock failure' } });
      if (path === '/api/images') return route.fulfill({ json: { imageUrl: image } });
      if (path === '/api/products' || path === '/api/products/1') return route.fulfill({ json: product });
      if (path === '/api/admin/orders/1/status') order = { ...order, status: json.status };
      if (path === '/api/admin/orders/1/delivery-status') order = { ...order, deliveryStatus: json.deliveryStatus };
      if (path.startsWith('/api/admin/orders/')) return route.fulfill({ json: order });
      if (path === '/api/categories') categories.push({ id: 3, ...json, children: [] });
      if (path === '/api/categories/2' && request.method() === 'PUT') categories[0].children[0] = { ...categories[0].children[0], ...json };
      if (path === '/api/option-groups') groups.push({ id: 3, ...json, values: [] });
      if (path === '/api/option-groups/1' && request.method() === 'PUT') groups[0] = { ...groups[0], ...json };
      if (path === '/api/option-groups/1/values') groups[0].values.push({ id: 3, groupId: 1, groupName: '사이즈', ...json });
      if (path === '/api/option-groups/values/1' && request.method() === 'PUT') groups[0].values[0].name = json.name;
      if (path === '/api/option-groups/values/1' && request.method() === 'DELETE') groups[0].values = groups[0].values.filter(value => value.id !== 1);
      if (path === '/api/admin/posts/12' && request.method() === 'PUT') posts[0].title = '수정한 게시글';
      return route.fulfill({ json: envelope(null) });
    }
    if (fail === path) return route.fulfill({ status: 500, json: { message: 'mock failure' } });
    if (path === '/api/admin/posts') return route.fulfill({ json: envelope(paged(empty ? [] : posts)) });
    if (path === '/api/admin/posts/12') return route.fulfill({ json: envelope(posts[0]) });
    if (path === '/api/products') return route.fulfill({ json: { items: empty ? [] : [{ id: 1, skuId: 2, name: product.name, imageUrl: image, status: 'ACTIVE', price: 19000, totalStock: 12 }], totalCount: empty ? 0 : 1, currentPage: 0, totalPages: 1, hasNext: false } });
    if (path === '/api/products/1') return route.fulfill({ json: product });
    if (path === '/api/categories') return route.fulfill({ json: envelope(empty ? [] : categories) });
    if (path === '/api/option-groups') return route.fulfill({ json: empty ? [] : groups });
    if (path === '/api/admin/orders') return route.fulfill({ json: paged(empty ? [] : [order]) });
    if (path === '/api/admin/orders/1') return route.fulfill({ json: order });
    return route.fulfill({ status: 501, json: { message: 'Unmocked API: ' + path } });
  });
  await page.goto(origin);
  await page.evaluate(() => localStorage.setItem('auth-storage', JSON.stringify({ state: { user: { id: 99, name: '관리자', email: 'admin@example.invalid', role: 'ROLE_ADMIN' }, accessToken: 'local-mock-only', refreshToken: null }, version: 0 })));
  const paths = ['/admin/posts', '/admin/posts/12', '/admin/products', '/products/new', '/admin/products/1/edit', '/admin/orders', '/admin/orders/1', '/admin/categories', '/admin/option-groups'];
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: 900 });
    for (const path of paths) {
      await page.goto(origin + path);
      await page.getByRole('heading', { level: 1 }).waitFor();
      await page.waitForFunction(() => ![...document.querySelectorAll('[role="status"]')].some(el => el.textContent.includes('불러오는')));
      check(!await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), width + ' overflow: ' + path);
      if (width === 1440) check(await page.getByRole('navigation', { name: '관리자 메뉴' }).locator('[aria-current="page"]').count() === 1, 'Exactly one current menu: ' + path);
      if (width !== 320) await page.screenshot({ path: '/tmp/admin-market-' + width + '-' + path.replaceAll('/', '_') + '.png', fullPage: true });
    }
    results.push(width + 'px: nine screens, no overflow');
  }
  await page.goto(origin + '/admin/posts');
  await page.getByLabel('제목·내용·작성자 검색').fill('없는 검색어');
  await page.getByText('검색 결과가 없습니다.', { exact: true }).waitFor();
  await page.getByRole('button', { name: '조건 초기화' }).click();
  await page.getByRole('button', { name: '수정', exact: true }).click();
  let modal = page.getByRole('dialog', { name: '게시글 수정' });
  await modal.getByLabel('제목 (필수)').fill('');
  await modal.getByRole('button', { name: '저장', exact: true }).click();
  await modal.getByText('제목은 1~200자, 내용은 1자 이상 입력해 주세요.').waitFor();
  check(writes.length === 0, 'Invalid post must not send');
  await modal.getByLabel('제목 (필수)').fill('수정한 게시글');
  pending = true;
  await modal.getByRole('button', { name: '저장', exact: true }).click();
  await modal.getByRole('button', { name: '저장 중…' }).waitFor();
  check(await modal.getByRole('button', { name: '취소' }).isDisabled(), 'Post pending lock');
  release(); pending = false;
  await modal.waitFor({ state: 'hidden' });
  check(writes[0].method === 'PUT' && writes[0].raw.includes('name="title"') && !writes[0].raw.includes('name="content"'), 'Only changed multipart post fields');
  results.push('post search/reset, validation, pending, unchanged multipart API');
  await page.goto(origin + '/products/new');
  await page.getByLabel('상품명 (필수)').fill('새 상품');
  await page.getByLabel('카테고리 (필수)').selectOption('1');
  await page.getByLabel('옵션 사용').check();
  await page.getByRole('combobox', { name: '옵션 그룹', exact: true }).selectOption('1');
  await page.getByRole('button', { name: 'S', exact: true }).click();
  await page.getByRole('button', { name: 'M', exact: true }).click();
  await page.getByText('선택한 값으로 2개 SKU 조합을 만듭니다.').waitFor();
  for (const index of [1, 2]) { await page.getByLabel('가격 ' + index + ' (원)').fill('19000'); await page.getByLabel('재고 ' + index + ' (개)').fill('12'); }
  const imageResponse = await page.request.get(image);
  await page.getByLabel('대표 이미지 선택').setInputFiles({ name: 'local-test.png', mimeType: 'image/png', buffer: await imageResponse.body() });
  await page.getByRole('button', { name: '상품 등록', exact: true }).click();
  await page.waitForURL('**/admin/products');
  const created = writes.find(write => write.path === '/api/products' && write.method === 'POST');
  check(created.json.skus.length === 2 && created.json.imageUrl === image && created.json.skus.every(sku => sku.optionValueIds.length === 1), 'SKU and uploaded-image create contract');
  await page.goto(origin + '/admin/products/1/edit');
  await page.getByLabel('가격 1 (원)').fill('20000');
  await page.getByRole('button', { name: '변경 저장', exact: true }).click();
  await page.waitForURL('**/admin/products');
  const edited = writes.find(write => write.path === '/api/products/1' && write.method === 'PATCH');
  check(edited.json.skus[0].id === 2 && edited.json.skus[0].price === 20000 && edited.json.status === 'ACTIVE', 'Existing SKU ids preserved');
  results.push('option combinations, image upload, product create/update, SKU ids');
  await page.goto(origin + '/admin/orders/1');
  await page.getByRole('combobox', { name: '주문 상태', exact: true }).selectOption('COMPLETED');
  await page.getByRole('combobox', { name: '배송 상태', exact: true }).selectOption('SHIPPING');
  await page.getByRole('button', { name: '변경 저장', exact: true }).click();
  modal = page.getByRole('dialog', { name: '주문 상태를 변경하시겠어요?' });
  failDelivery = true;
  await modal.getByRole('button', { name: '확인하고 저장' }).click();
  await modal.getByRole('button', { name: '최신 상태 확인' }).waitFor();
  check(order.status === 'COMPLETED' && order.deliveryStatus === 'READY', 'Partial success fixture');
  check(await modal.getByRole('button', { name: '확인하고 저장' }).count() === 0, 'No blind retry after partial failure');
  failDelivery = false;
  await modal.getByRole('button', { name: '최신 상태 확인' }).click();
  await modal.waitFor({ state: 'hidden' });
  check(await page.getByRole('combobox', { name: '주문 상태', exact: true }).inputValue() === 'COMPLETED', 'Latest order status restored');
  check(await page.getByRole('combobox', { name: '배송 상태', exact: true }).inputValue() === 'READY', 'Latest delivery status restored');
  results.push('order confirmation, two PATCH APIs, partial-failure recovery');
  await page.goto(origin + '/admin/categories');
  await page.getByText('강아지', { exact: true }).click();
  check(await page.getByRole('button', { name: '삭제', exact: true }).isDisabled(), 'Parent delete prohibited');
  await page.locator('summary').filter({ hasText: '강아지' }).click();
  await page.getByText('산책용품', { exact: true }).first().click();
  const beforeEdit = writes.length;
  await page.getByRole('button', { name: '수정하기', exact: true }).click();
  check(writes.length === beforeEdit, 'Entering edit mode must not submit unchanged category');
  await page.getByLabel('카테고리 이름 (필수)').fill('산책 준비');
  await page.getByRole('button', { name: '저장', exact: true }).click();
  await page.getByText('카테고리가 수정되었습니다.', { exact: true }).waitFor();
  check(writes.some(write => write.path === '/api/categories/2' && write.method === 'PUT' && write.json.parentId === 1), 'Category update contract');
  await page.getByText('산책 준비', { exact: true }).first().waitFor();
  await page.getByRole('button', { name: '새 카테고리' }).click();
  check(await page.getByRole('button', { name: '저장', exact: true }).count() === 1, 'New category enters editable create mode');
  await page.getByLabel('카테고리 이름 (필수)').fill('새 분류');
  await page.getByRole('button', { name: '저장', exact: true }).click();
  await page.getByText('카테고리가 생성되었습니다.', { exact: true }).waitFor();
  await page.goto(origin + '/admin/option-groups');
  await page.getByRole('button', { name: '사이즈', exact: true }).click();
  check(await page.getByRole('button', { name: '그룹 삭제', exact: true }).isDisabled(), 'Nonempty group delete prohibited');
  const beforeGroupEdit = writes.length;
  await page.getByRole('button', { name: '그룹 수정', exact: true }).click();
  check(writes.length === beforeGroupEdit, 'Entering group edit must not submit unchanged group');
  await page.getByLabel('그룹 이름 (필수)').fill('의류 사이즈');
  await page.getByRole('button', { name: '저장', exact: true }).click();
  await page.getByText('옵션 그룹이 수정되었습니다.', { exact: true }).waitFor();
  await page.getByRole('button', { name: '의류 사이즈', exact: true }).waitFor();
  await page.getByLabel('추가할 옵션 값').fill('L');
  await page.getByRole('button', { name: '옵션 값 추가', exact: true }).click();
  await page.getByText('옵션 값이 추가되었습니다.', { exact: true }).waitFor();
  await page.getByRole('button', { name: '수정', exact: true }).first().click();
  await page.getByLabel('옵션 값 수정').fill('XS');
  await page.getByRole('button', { name: '저장', exact: true }).click();
  await page.getByText('옵션 값이 수정되었습니다.', { exact: true }).waitFor();
  await page.getByRole('button', { name: '삭제', exact: true }).first().click();
  modal = page.getByRole('dialog', { name: '삭제하시겠어요?' });
  await modal.getByRole('button', { name: '삭제', exact: true }).click();
  await modal.waitFor({ state: 'hidden' });
  check(writes.some(write => write.path === '/api/option-groups/values/1' && write.method === 'DELETE'), 'Option-value delete contract');
  results.push('category create/update/parent guard, group edit without auto-submit, option-value create/update/delete');
  for (const [path, api] of [['/admin/posts', '/api/admin/posts'], ['/admin/products', '/api/products'], ['/admin/orders', '/api/admin/orders'], ['/admin/categories', '/api/categories'], ['/admin/option-groups', '/api/option-groups']]) {
    fail = api;
    await page.goto(origin + path);
    await page.getByRole('alert').waitFor({ timeout: 15000 });
    check(await page.getByText('검색 결과가 없습니다.', { exact: true }).count() === 0, 'Error is not empty: ' + path);
    fail = ''; empty = true;
    await page.getByRole('button', { name: '다시 불러오기', exact: true }).click();
    await page.getByRole('alert').waitFor({ state: 'hidden' });
    empty = false;
  }
  results.push('five list errors, retry and empty-result recovery');
  await page.route('**/favicon-96.png', route => route.abort());
  await page.goto(origin + '/admin/products/1/edit');
  await page.getByRole('img', { name: '상품 대표 이미지 미리보기 · 이미지를 불러오지 못했습니다.' }).waitFor();
  await page.unroute('**/favicon-96.png');
  results.push('product image failure fallback');
  check(errors.length === 0, 'Page errors: ' + errors.join('; '));
  return { results, screensRendered: 27, screenshotCount: 18, mockedWrites: writes.length, pageErrors: errors };
}
