async page => {
  const checks=[];
  const check=(ok,label)=>{if(!ok)throw new Error(label);checks.push(label);};
  const gateway='http://127.0.0.1:18180';
  const backend='http://127.0.0.1:18081';
  const before=await (await page.request.get(backend+'/__fixture/requests')).json();
  await page.route('**/api/**',async route=>{
    const suffix=route.request().url().split('/api/')[1];
    if(!/^places(?:[/?]|$)/.test(suffix) || route.request().method()!=='GET')return route.abort();
    const response=await route.fetch({url:gateway+'/api/'+suffix,maxRedirects:0,maxRetries:0});
    await route.fulfill({response});
  });
  const listing=await page.request.get(gateway+'/api/places?areaCode=36110');
  check(listing.status()===200 && (await listing.json()).availability==='READY','gateway returns stored READY list');
  check((await page.request.post(gateway+'/api/places')).status()===404,'no public collection write endpoint');
  for(const [path,status] of [['/api/places?areaCode=99',400],['/api/places/999',404]]) {
    check((await page.request.get(gateway+path)).status()===status,'stored API status '+status);
  }
  await page.setViewportSize({width:1440,height:1000});
  await page.goto('http://127.0.0.1:5197/travel?areaCode=36110');
  await page.getByRole('heading',{name:'통합 검증 장소',exact:true}).waitFor();
  check(await page.getByText('사진 준비 중',{exact:true}).count()===3,'missing licensed photos keep fallback');
  await page.getByRole('link',{name:/세종특별자치시 동반 안내 미제공 장소/}).click();
  await page.getByText('동반 조건 확인 중입니다.',{exact:false}).waitFor();
  const pending=await (await page.request.get(gateway+'/api/places/124')).json();
  check(pending.petInformationStatus==='PREPARING' && pending.petInformationFetchedAt===null,'DB basic detail is public before enrichment');
  check((await (await page.request.get(backend+'/__fixture/requests')).json()).requests===before.requests,'basic browsing does not collect details');
  const enriched=await (await page.request.post(backend+'/__fixture/enrich')).json();
  check(enriched.status==='PARTIAL' && enriched.published===1,'bounded collector enriches one while another is pending');
  await page.reload();
  await page.getByText('제공된 동반 조건 정보가 없습니다.',{exact:false}).waitFor();
  const empty=await (await page.request.get(gateway+'/api/places/124')).json();
  check(empty.petInformationStatus==='READY' && Boolean(empty.petInformationFetchedAt),'successful empty conditions have their own timestamp');
  const waiting=await (await page.request.get(gateway+'/api/places/125')).json();
  check(waiting.petInformationStatus==='PREPARING','third place remains in enrichment queue');
  const hidden=await (await page.request.post(backend+'/__fixture/hide')).json();
  check(hidden.status==='COMPLETED' && hidden.published===0,'inventory hides pending place before attempting its details');
  check((await page.request.get(gateway+'/api/places/125')).status()===404,'hidden pending place is unavailable by direct URL');
  const stored=await (await page.request.get(gateway+'/api/places?areaCode=36110')).json();
  check(stored.items.length===2,'hidden pending place removed from list');
  const browsingStart=await (await page.request.get(backend+'/__fixture/requests')).json();
  await page.goto('http://127.0.0.1:5197/travel?areaCode=36110');
  await page.getByRole('heading',{name:'통합 검증 장소',exact:true}).waitFor();
  await page.getByRole('link',{name:/세종특별자치시 통합 검증 장소/}).click();
  await page.getByText('목줄 착용·배변 봉투 지참',{exact:true}).waitFor();
  check(page.url().endsWith('/travel/123?areaCode=36110'),'DB detail preserves region');
  check(await page.getByText('관광정보·사진 제공:',{exact:false}).count()===1,'source shown once');
  await page.getByRole('link',{name:'세종특별자치시 목록으로'}).click();
  check(await page.getByLabel('지역 (시·도)').inputValue()==='36110','back restores region');
  await page.getByLabel('지역 (시·도)').selectOption('26');
  await page.getByText('현재 표시할 장소가 없어요',{exact:true}).waitFor();
  checks.push('completed empty region distinguished');
  await page.getByLabel('지역 (시·도)').selectOption('51');
  await page.getByText('장소 정보를 준비 중이에요',{exact:true}).waitFor();
  check(await page.getByText('현재 표시할 장소가 없어요',{exact:true}).count()===0,'uncollected region is not presented as empty');
  await page.setViewportSize({width:375,height:812});
  await page.goto('http://127.0.0.1:5197/travel?areaCode=36110');
  await page.getByRole('heading',{name:'통합 검증 장소',exact:true}).waitFor();
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile list no overflow');
  await page.getByRole('link',{name:/세종특별자치시 통합 검증 장소/}).click();
  await page.getByText('목줄 착용·배변 봉투 지참',{exact:true}).waitFor();
  check(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile detail no overflow');
  await page.request.post(backend+'/__fixture/failure');
  await page.goto('http://127.0.0.1:5197/travel?areaCode=36110');
  await page.getByRole('status').filter({hasText:'갱신이 지연'}).waitFor();
  check(await page.getByRole('heading',{name:'통합 검증 장소',exact:true}).count()===1,'failed refresh still displays published DB place');
  const after=await (await page.request.get(backend+'/__fixture/requests')).json();
  check(before.requests===5 && browsingStart.requests===13 && after.requests===browsingStart.requests,'public browsing performs zero provider requests outside explicit fixture collection');
  return {count:checks.length,checks,actualGateway:true,actualMySql:true,actualCollector:true,providerFixture:true};
}
